Adds an Author
aurabindo/vaken-cli pull request #1
Opened 2019-02-03 04:00 UTC by pitankar

Adds Namrata's name as an Author into the README.md

Signed-off-by: Piyush Itankar <pitankar@gmail.com>

2019-02-03 06:05 UTC, aurabindo requested changes
@pitankar Can you please remove the formatting commit from this PR? Tabs are better than spaces: https://softwareengineering.stackexchange.com/a/72

2019-02-03 06:06 UTC, aurabindo approved these changes

2019-02-03 06:06 UTC, aurabindo requested changes
@pitankar Can you please remove the formatting commit from this PR? Tabs are better than spaces: https://softwareengineering.stackexchange.com/a/72

2019-02-03 07:07 UTC, pitankar commented
The code originally had a mix of Tabs and Spaces for indentation. It was unreadable (the inner for loop) as below:
![indent](https://user-images.githubusercontent.com/2120983/52173709-722fb500-27af-11e9-9134-9cb9358ec05c.png)

I decided to go for space thinking that in our case the code has to look right on all machines and in all editors. Tabs are good (agree with all reasons mentioned) but they screw up parameter alignment in case of a multi-line function (I believe future updates might have such functions with many parameters). Folks wanting to do a crypt analysis would want to open the source code and read right away. Having to deal with the editor first is a pain, also copy pasting in different environment (like matlab, octav, python etc) where one might want to port the code and make minor changes will be more easy.

2019-02-03 07:28 UTC, aurabindo commented
> The code originally had a mix of Tabs and Spaces for indentation. 

Yeah back then, we weren't event kids. We were just infants ;) 

I prefer to have tabs everywhere. I am of the opinion that if a function takes too many arguments or if they are too long, then it is a design problem. All code must be formatted to 80 column limit. Not because our screens arent larger than 80 chars, but it allows compact view without wasting horizontal real estate on screen. Very useful when in split mode in vim/emacs/etc. 

But this code base is in a outdated(autotools!), pathetic(we were infants, remember) horrible(not formatting style fixed early on) and scary(not generously commented) state that nobody will ever read it through. I consider this code to be just a proof of concept and not a reference implementation. Nevertheless, since you insist, I'll take it in.

2019-02-03 07:29 UTC, aurabindo approved these changes

2019-02-03 07:31 UTC, merged

2019-02-07 16:40 UTC, pitankar commented
Thanks. I think we should start to iron out the details around code quality and code organisation.

2019-02-09 12:33 UTC, aurabindo commented
I prefer not to waste much time on this code base. As I said, this is a PoC. We need a different reference implementation. But even before we embark on that, we need to sort out some technical details of algorithm. I'll message you privately.